projeto_integrador2/core/urls.py
from django.urls import path
from . import views
from .views import DetalheListView
app_name = "core"
urlpatterns =[
    
    path("", views.LoginPageView.as_view(), name="Login"),
    path("home", views.HomePageView.as_view(), name="home"),
    path("home/privacidade/", views.PrivacidadePageView.as_view(), name="privacidade"),
    path("home/legal/terms/", views.LegalTermsPageView.as_view(), name="legal_terms"),
    path("menu/", views.MenuPageView.as_view(), name="menu"),
    path("menu/inicio/", views.InicioPageView.as_view(), name="inicio"),
    #path("menu/detalhes/", DetalheListView.as_view(), name="detalhes"),
    #path("menu/detalhes/", views.DetalhesPageView.as_view(), name="detalhes"),
    path("menu/detalhes/", views.saldo_total, name="saldo_total"),
    path("menu/despesas_categoria/", views.DespesasCategoriaPageView.as_view(), name="despesas_categoria"),
    path("menu/planejamento_despesas/", views.PlanejamentoDespesasPageView.as_view(), name="planejamento_despesas"),
    
    path('orcamento/<int:id>/', views.saldo_receita, name='saldo_receita'),
    path("menu/contas_a_pagar/", views.Contas_a_PagarPageView.as_view(), name="contas_a_pagar"),
    #path("menu/porCategoria/", views.PorCategoriaPageView.as_view(), name="porCategoria"),
    path("menu/modalGenerico/", views.ModalGenericoPageView.as_view(), name="modalGenerico"),
    #path("menu/modalPerfil/", views.#ModalPerfilPageView.as_view(), #name="modalPerfil"),
    path("menu/modalPerfilAparencia/", views.ModalPerfilAparenciaPageView.as_view(), name="modalPerfilAparencia"),

    ####################
    # TODO: Register create view
    path('menu/administrador/register', views.AdministradorCreateView.as_view(), name='administrador_register'), 
     # TODO: Register create view
    path('menu/blog/register', views.BlogCreateView.as_view(), name='blog_register'),
    # TODO: Register create view
    


    ####Despesas    
    path('menu/despesas/',views.Despesas_html,name='despesas_register'),
    path('menu/despesas/despesas_cadastro/', views.despesas_cadastro),
    path('menu/despesas/despesas_cadastro/submit', views.Submit_despesas_cadastro,name='despesas_submit'),
    path('menu/despesas/delete/<int:id_despesas>/', views.Delete_despesas,name='despesas_delete' ),
    #Fim Despesas   


    ####Receita    
    path('menu/receita/',views.Receita_html,name='receita_register'),
    path('menu/receita/receita_cadastro/', views.receita_cadastro),
    path('menu/receita/receita_cadastro/submit', views.Submit_receita_cadastro,name='despesas_submit'),
    path('menu/receita/delete/<int:id_receita>/', views.Delete_receita,name='receita_delete' ),
    #Fim Receita  


    ####BLog    
    path('menu/blog/',views.Blog_html,name='blog_register'),
    path('menu/blog/blog_cadastro/', views.blog_cadastro),
    path('menu/blog/blog_cadastro/submit', views.Submit_blog_cadastro,name='blog_submit'),
    path('menu/blog/delete/<int:id_blog>/', views.Delete_blog,name='blog_delete' ),
    #Fim Blog      


]

projeto_integrador2/projeto_integrador2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('core.urls', namespace='core')),
    
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto_integrador2/core/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
# TODO: Import reverse
from django.urls import reverse


# Create your models here.
#Administrador

class Administrador(models.Model):
    titulo=models.CharField(max_length=50,null=True,blank=True,verbose_name='Titulo')
    nome_social=models.CharField(max_length=50,null=True,blank=True,verbose_name='Autor')
    email=models.EmailField(max_length=50,)
    telefone=models.IntegerField(null=True,blank=True,verbose_name='Telefone')
    # TODO: Add get_absolute_url
    def get_absolute_url(self):
        return reverse('administrador_detail', kwargs={"pk": self.pk})    
    def __str__(self):
        return self.titulo

class Blog(models.Model):
    titulo=models.CharField(max_length=50,null=True,blank=True,verbose_name='Título')
    img=models.ImageField(upload_to='images/',null=True,blank=True,verbose_name='Imagem')
    texto=models.TextField(max_length=200,null=True,blank=True,verbose_name='Texto')
    link=models.URLField()
    auto_data=models.DateField(null=True,blank=True,verbose_name='Data')  
    def __str__(self):
        return self.titulo

#Usuario


class Receita(models.Model):
    titulo=models.CharField(null=True,blank=True,max_length=50,verbose_name='Título')
    recorrente=models.BooleanField(default=False,null=True,blank=True,verbose_name='Recorrente')
    produto=models.CharField(max_length=50,verbose_name='Produto')
    valor=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='Valor', default=0)
    auto_data=models.DateField(null=True,blank=True,verbose_name='Data')
    status=models.BooleanField(default=False,null=True,blank=True,verbose_name='Status')
    total_receber=models.DecimalField(max_digits=10, decimal_places=2, editable=False,verbose_name='Total', default=None)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.titulo  + ",R$" + str(self.valor) +"," + "R$" +str(self.total_receber)

        #calculo
    def save(self, *args, **kwargs):
        self.total_receber = (self.valor)
        #self.total_receber.save()
        return super (Receita, self).save(*args, **kwargs)
    

class Despesas(models.Model):
    titulo=models.CharField(null=True,blank=True,max_length=50,verbose_name='Título')
    recorrente=models.BooleanField(default=False,null=True,blank=True,verbose_name='Recorrente')
    produto=models.CharField(max_length=50,verbose_name='Produto')
    valor=models.DecimalField(max_digits=10, decimal_places=2)
    auto_data=models.DateField(null=True,blank=True,verbose_name='Data')
    status=models.BooleanField(default=False,null=True,blank=True,verbose_name='Status')
    total_pago=models.DecimalField(max_digits=10, decimal_places=2,editable=False,verbose_name='Total', default=None)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)#
    def __str__(self):
        return self.titulo  + ",R$" + str(self.valor) +"," + "R$" +str(self.total_pago)

        #calculo
    def save(self, *args, **kwargs):
        self.total_pago = self.valor
        #self.total_pago.save()
        return super (Despesas, self).save(*args, **kwargs)
       
#https://jaketrent.com/post/add-migration-nonnull-foreignkey-field-django

projeto_integrador2/templates/base2.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}nome do site{% endblock %}</title>
</head>
{% if user.is_authenticated %}
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">


                <a class="navbar-brand" href='/'> Menu</a>
                <ul class="navbar-nav">

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:detalhes' %}">teste filtros saldo</a>
                    </li> 


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:receita_register' %}">receita</a>
                    </li> 
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:blog_register' %}">blog</a>
                    </li>    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:despesas_register' %}">despesas</a>
                    </li>                                                              

                </ul>
            </div>
        </nav>


    </header>
    {% endif %}   
</body>
</html>

projeto_integrador2/templates/base_seguranca.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}nome do site{% endblock %}</title>
</head>

<body>
    

</body>

</html>

projeto_integrador2/templates/boostrap_5.html
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>pi2</title>
  </head>
  {% if user.is_authenticated %}
  <body>
    

 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block content %}
    {% endblock %}




    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  
  </body>
  {% endif %}
</html>

projeto_integrador2/templates/despesas.html
{% if user.is_authenticated %}
<!--Página despesas-->
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}nome do site{% endblock %}</title>
</head>

<nav>

    <a href="/menu/"> <button type="submit">Menu</button> </a>
</nav>
<div class="principal">
    <h2>Despesas</h2>
    <nav><a href="despesas_cadastro/"> <button type="button">Novo</button></a></nav>
    <div>
            <table>
                <tr>
                    <th>Protocolo</th>
                    <th>Título</th>
                    <th>Recorrente</th>
                    <th>Valor</th>
                    <th>Status</th>
                    <th>Total pago</th>
                </tr>
                {% for evento_despesas in eventos %}
                <tr>
                    <td>{{ evento_despesas.id }}</td> <!--Id-->
                    <td>{{ evento_despesas.titulo }}</td> <!--Produto-->
                    <td>{{ evento_despesas.recorrente }}</td> <!--Recorrente-->
                    <td>{{ evento_despesas.produto }}</td> <!--Produto-->
                    <td>{{ evento_despesas.valor }}</td> <!--Valor-->
                    <td>{{ evento_despesas.status }}</td> <!--Status-->
                    <td>{{ evento_despesas.total_pago }}</td> <!--Total_pago-->
                    <td><a href="despesas_cadastro/?id={{ evento_despesas.id }}">Editar</a></td>
                    <td><a href="delete/{{ evento_despesas.id }}/">Excluir</a></td>
                </tr>
                {% endfor %}
            </table>
    </div>
</div>
</header>
</body>
</html>
{% endif %}

projeto_integrador2/templates/despesas_cadastro.html
{% if user.is_authenticated %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}nome do site{% endblock %}</title>
</head>

<nav>

    <a href="/menu/despesas/"> <button type="submit">Voltar</button> </a>
</nav>    
<main>
    
    <h2>Despesas cadastro</h2>
    <form action="submit" method="POST">{% csrf_token %}
        <div>
            <fieldset class="module aligned ">
    
    
    
                <div class="form-row field-titulo">
                    
                    
                        <div>
                            
                            
                                <label for="id_titulo">Título:</label>
                                        <select class="form-select" size="4" aria-label="size 3 select example" id="id_titulo">
                                                <option selected>Open this select menu</option>
                                                <option value="Essencial">Essencial</option>
                                                <option value="Não essencial">Não essencial</option>
                                                <option value="Investimento">Investimento</option>
                                        </select>
                                        <!-- <input type="text" name="titulo" class="vTextField" maxlength="50" id="id_titulo" value="{{evento_despesas.titulo}}" required > -->
                                
                            
                            
                        </div>
                    
                </div>
            
                <div class="form-row field-recorrente">
                    
                    
                        <div>
                            
                            
                                <label for="id_recorrente">Recorrente:</label>
                                
                                    <select name="recorrente" id="id_recorrente">

        
          <option value="True">Sim</option>
        
          <option value="False" selected>Não</option>
        
        </select>
                                
                            
                            
                        </div>
                    
                </div>
            
                <div class="form-row field-produto">
            
            
                    <div>
                        
                        
                            <label class="required" for="id_produto">Produto:</label>
                            
                                <input type="text" name="produto" class="vTextField" maxlength="50" required id="id_produto" value="{{evento_despesas.produto}}">
                            
                        
                        
                    </div>
                
            </div>
            
                <div class="form-row field-valor">
                    
                    
                        <div>
                            
                            
                                <label class="required" for="id_valor">Valor:</label>
                                
                                    <input type="number" name="valor" step="0.01" required id="id_valor">
                                
                            
                            
                        </div>
                    
                </div>
            
                <div class="form-row field-auto_data">
                    
                    
                        <div>
                            
                            
                                <label for="id_auto_data">Data:</label>
                                
                                    <input type="date" name="auto_data"  id="id_auto_data" required>
                                
                            
                            
                        </div>
                    
                </div>
            
                <div class="form-row field-status">
                    
                    
                        <div>
                            
                            
                                <label for="id_status">Status:</label>
                                
                                    <select name="status" id="id_status">

        
          <option value="True">Devendo</option>
        
          <option value="False" selected>Pago</option>
        
        </select>
                                
                            
                            
                        </div>
                    
                </div>
            
                <div class="form-row field-total_pago">
                    
                    
                        <div>
                            
                            
                                <label for="id_total_pago">Total:</label>
                                
                                    <input type="number" name="total_pago" step="0.01" id="id_total_pago" required >
                                
                            
                            
                        </div>
                    
                </div>
            
        </fieldset>
        
        
        
        
        
        
        
        
        
        
        
        <input type="hidden" name="id" value="{{ evento_despesas.id }}">
        
        <div class="submit-row">
        
            <div>
          

                <button type="submit">Salvar_</button></a>         
                </div>
        
        
        </div>
        
        
          
          
          
          
          
          
          
          
          
          
          
          
          

          

    </form>    
</main>
</header>
</body>
</html>
{% endif %}

projeto_integrador2/templates/detalhes.html
{% extends }

{% block content %}

<!--CAIXA SELEÇÃO MÊS - COMBOBOX-->

<!--SALDO ***é um extends***-->

<!--DETALHES-->
<!--aqui virá uma tabela com filtro de todas as entradas do mês X-->

<form class="row">
    <label>Pesquisar Mês</label>
      <input type="month" id="mes" name="mes-pesquisa" placeholder="Digite  mês">
    <button type="submit">Pesquisar</button>
</form>

<h2> A MÊS PESQUISADO<u> {{ saldotot.termodapesquisa }} </u></h2>
<br>
<p> B {{ saldotot.saldo_receita }}</p>
<p> C {{ saldotot.saldo_despesas }}</p>
<p> D Ocorrências de Receita no mês {{ saldotot.query_rec }}</p>
<p> E Ocorrências de Despesas no mês {{ saldotot.query_desp }}</p>
<br>
<h3> F RECEITA R$ {{ saldotot.tot_rec }}</h3>
<H3> G DESPESA R$ {{ saldotot.tot_desp }}</H3>
<br>
<h1><b> SALDO MENSAL  <u>R$ {{ saldotot.saldo_mensal }}</u> </b></h1>

{% endblock %}

projeto_integrador2/templates/home.html
{% extends 'base.html' %}

{% block title %}nome do site{% endblock %}

{% block content %}
        {{ saldo_receita.total_receber }}
{% endblock %}

projeto_integrador2/templates/inicio.html
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load("current", {packages:["corechart"]});
  google.charts.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Categoria', 'Despesas'],
      ['essenciais',    1395.00],
      ['não essenciais',  220.0],
      ['investimentos',   118.0],
      ['não atribuídos',  767.0]
    ]);

    var options = {
      title: 'Despesas por categoria',
      pieHole: 0.6,
      pieSliceText: 'none',
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
    chart.draw(data, options);
  }
</script>

{% block content %}



<!-- BEM VINDO -->


<div>
    <h1>Bom dia, Usuário</h1>
</div>

<!-- RESUMO DE SALDO//DESPESA//RECEITAS  *****isso será um stands*****-->
<div class="PESQUISAR" id="saldo">
    <div>
        <!--label saldo-->
        <!--valor saldo-->
        <div>
            <div>
                <img>
            </div>
        </div>
        
    </div>

</div>

<!-- BOTÕES DE AÇÃO RÁPIDA -->

<div>
    <a href="/menu/receita/receita_cadastro/"><button type="button" class="btn btn-primary btn-lg">+</button></a>
    <a href="/menu/despesas/despesas_cadastro/"><button type="button" class="btn btn-primary btn-lg">-</button></a>
</div>


<!-- CONTAS A PAGAR -->



<!-- DESPESAS POR CATEGORIA -->

<div>
    <div id="donutchart" style="width: 300px; height: 300px;"></div>
</div>

<!-- BLOG -->
<!-- cards bootstrap deslizando horizontalmente -->


{% endblock %}

projeto_integrador2/templates/menu.html
{% extends 'boostrap_5.html' %}



{% block content %}


{# TODO: Add link to registration page #}




<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Menu</a>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <li class="nav-item">
            <a class="nav-link" href="/menu/inicio/">Início</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/menu/detalhes">Detalhes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/menu/despesas_categoria/">Despesas por categoria</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/menu/planejamento_despesas/">Planejamento de despesas</a>
          </li>

        </ul>

      </div>
    </div>
  </nav>



{% endblock %}

projeto_integrador2/templates/modalGenerico.html
{% extends 'base2.html' %}



{% block content %}
    Olá!
{% endblock %}

projeto_integrador2/templates/modalPerfilAparencia.html
{% extends 'base2.html' %}



{% block content %}
    Olá!
{% endblock %}

projeto_integrador2/templates/privacidade.html
{% extends 'base2.html' %}



{% block content %}
    <p>Aviso de Privacidade sobre sites, comunicação e cookies
        segunda-feira, 28 de fevereiro de 2022
        Nós nos importamos com sua privacidade. Quando a Mozilla (ou seja, nós) coleta informações sobre você, nossa Política de privacidade da Mozilla descreve de que forma gerenciamos essas informações.
        
        Este aviso de privacidade se aplica aos sites e aplicativos móveis administrados pela Mozilla, inclusive os domínios mozillians.org, mozilla.org, firefox.com, entre outros. Eles incluem, por exemplo, foundation.mozilla.org, bugzilla.mozilla.org, reps.mozilla.org, careers.mozilla.org, developers.mozilla.org, support.mozilla.org, addons.mozilla.org e wiki.mozilla.org.
        
        O que você deve saber
        Podemos receber suas informações pessoais com base em sua interação conosco em plataformas de redes sociais: ao se candidatar a uma vaga de emprego, estágio, subvenção ou bolsa, ao atuar como membro voluntário da comunidade Mozilla, ao nos enviar feedback ou uma solicitação, ao se inscrever em uma conta ou fazer uma assinatura ou ao interagir com uma campanha de produto ou política. 
        
        Podemos usar cookies, GIFs transparentes, análises da web de terceiros, informações de dispositivos e endereços IP para oferecer a funcionalidade e para entender melhor a interação do usuário com nossos produtos, serviços e comunicações. 
        
        É possível controlar preferências individuais de cookies, indicar suas preferências de cookies para outras pessoas e cancelar o recebimento de análises da web e de ferramentas de otimização. 
        
        Alguns sites da Mozilla possibilitam fazer compras (como aplicativos ou produtos), contribuir com projetos específicos da Mozilla ou fazer doações para programas públicos e de caridade da Mozilla. Essas transações são normalmente processadas por fornecedores terceirizados da Mozilla. </p>>
{% endblock %}

projeto_integrador2/templates/receita.html
{% if user.is_authenticated %}
<!--Página receita-->
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}nome do site{% endblock %}</title>
</head>

<nav>

    <a href="/menu/"> <button type="submit">Menu</button> </a>
</nav>
<div class="principal">
    <h2>Receita</h2>
    <nav><a href="receita_cadastro/"> <button type="button">Novo</button></a></nav>
    <div>
            <table>
                <tr>
                    <th>Id</th>
                    <th>Título</th>

                    <th>Recorrente</th>
                    <th>Produto</th>
                    <th>Valor</th>
                    <th>Status</th>
                    <th>Total Recebido</th>
                </tr>
                {% for evento_receita in eventos %}
                <tr>
                    <td>{{ evento_receita.id }}</td> <!--Id-->
                    <td>{{ evento_receita.titulo }}</td> <!--Produto-->
                    
                    <td>{{ evento_receita.recorrente }}</td> <!--Recorrente-->
                    <td>{{ evento_receita.produto }}</td> <!--Produto-->
                    <td>{{ evento_receita.valor }}</td> <!--Valor-->
                    <td>{{ evento_receita.status }}</td> <!--Status-->
                    
                    
                    
                    <td>{{ orcamento.total_receber }}</td> <!--total_receber-->
                    <td><a href="receita_cadastro/?id={{ evento_receita.id }}">Editar</a></td>
                    <td><a href="delete/{{ evento_receita.id }}/">Excluir</a></td>
                </tr>
                {% endfor %}
            </table>
    </div>
</div>
</header>
</body>
</html>
{% endif %}

projeto_integrador2/templates/saldo.html
{}